export const SHOW_EVENTS = 'SHOW_EVENTS';
export const SHOW_INITIATIVES = 'SHOW_INITIATIVES';
export const SHOW_FUNDRAISERS = 'SHOW_FUNDRAISERS';
export const SHOW_SCHOLARSHIPS = 'SHOW_SCHOLARSHIPS';
