export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_INITIATIVES = 'FETCH_INITIATIVES';
export const FETCH_FUNDRAISERS = 'FETCH_FUNDRAISERS';
export const FETCH_SCHOLARSHIPS = 'FETCH_SCHOLARSHIPS';
export const SET_INITIAL_STYLES = 'SET_INITIAL_STYLES';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
